// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeRoomie.Models;

#nullable disable

namespace OfficeRoomie.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OfficeRoomie.Models.Administrador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cpf")
                        .HasColumnType("longtext");

                    b.Property<string>("created_at")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("permissoes")
                        .HasColumnType("longtext");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("updated_at")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("administradores");
                });

            modelBuilder.Entity("OfficeRoomie.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cpf")
                        .HasColumnType("longtext");

                    b.Property<string>("created_at")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("endereco_bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("endereco_cep")
                        .HasColumnType("longtext");

                    b.Property<string>("endereco_cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("endereco_complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("endereco_estado")
                        .HasColumnType("longtext");

                    b.Property<string>("endereco_logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("endereco_numero")
                        .HasColumnType("longtext");

                    b.Property<string>("endereco_pais")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("updated_at")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
